name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm run build --if-present
      - name: Run Tests
        run: npm run test
        env:
          REACT_APP_API_SPACE_ID: ${{ secrets.REACT_APP_API_SPACE_ID }}
          REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}
          REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}